# Generated by Django 5.2 on 2025-05-01 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_order", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ordemservico",
            name="usuario",
            field=models.ForeignKey(
                help_text="Funcionário que abriu esta OS.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ordens_servico",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
