# Generated by Django 5.2 on 2025-05-06 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0004_remove_ordemservico_email_cliente_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='descricao',
            field=models.TextField(help_text='Descrição do serviço.'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='nome_cliente',
            field=models.CharField(help_text='Nome do técnico que solicitou.', max_length=100),
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(help_text='Sequência da etapa dentro da OS (ex: 1, 2, 3).')),
                ('status', models.CharField(choices=[('em_execucao', 'Em execução'), ('concluida', 'Concluída')], default='em_execucao', help_text='Status da etapa: em execução ou concluída.', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Comentário do técnico ao concluir a etapa.')),
                ('foto', models.ImageField(blank=True, help_text='Foto anexada pelo técnico ao concluir a etapa.', null=True, upload_to='stages/')),
                ('criado_em', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação da etapa.')),
                ('order', models.ForeignKey(help_text='Ordem de Serviço à qual esta etapa pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='app_order.ordemservico')),
                ('tecnico', models.ForeignKey(help_text='Técnico responsável pela etapa.', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'ordem'],
                'unique_together': {('order', 'ordem')},
            },
        ),
    ]
