# Generated by Django 5.2 on 2025-05-06 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0007_alter_stage_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='order',
            field=models.ForeignKey(blank=True, help_text='Ordem de Serviço (fica vazio se a OS for excluída).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stages', to='app_order.ordemservico'),
        ),
        migrations.AlterField(
            model_name='stage',
            name='tecnico',
            field=models.ForeignKey(blank=True, help_text='Técnico responsável (fica vazio se excluído).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
