# Generated by Django 5.2 on 2025-05-07 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0010_ordemservico_prazo_dias'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='prazo_dias',
        ),
    ]
