# Generated by Django 5.2 on 2025-05-12 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0011_remove_ordemservico_prazo_dias'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='prazo_estipulado',
            field=models.DateTimeField(blank=True, help_text='Data e hora estimada para a conclusão do serviço.', null=True),
        ),
    ]
