# Generated by Django 5.2 on 2025-05-13 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0012_ordemservico_prazo_estipulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='prazo_estipulado',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='prazo_inicial',
            field=models.DateTimeField(blank=True, help_text='Prazo inicial estimado para a conclusão do serviço.', null=True),
        ),
        migrations.AddField(
            model_name='stage',
            name='prazo_estipulado',
            field=models.DateTimeField(blank=True, help_text='Data e hora estimada para a conclusão desta etapa.', null=True),
        ),
    ]
