# Generated by Django 5.2 on 2025-05-25 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_order', '0013_remove_ordemservico_prazo_estipulado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='data_conclusao',
            field=models.DateTimeField(blank=True, help_text='Data e hora em que a OS foi marcada como concluída.', null=True),
        ),
    ]
